module.exports = [
{id:'gemini-pro',name:'Gemini Pro — 18 Months',category:'AI & Software',price:'Set price',stock:0},
{id:'netflix-4k',name:'Netflix 4K — Lifetime',category:'Streaming',price:'Set price',stock:10},
{id:'spotify',name:'Spotify Premium',category:'Streaming',price:'Set price',stock:2},
{id:'fortnite-accounts',name:'Fortnite Accounts — Instant Delivery',category:'Gaming',price:'Set price',stock:4},
{id:'fortnite-vbucks',name:'Fortnite V-Bucks Accounts',category:'Gaming',price:'Set price',stock:4},
{id:'discord-members',name:'Discord Real Server Members — Keys',category:'Discord',price:'Set price',stock:3},
{id:'claude-keys',name:'Claude Balance Keys',category:'AI & Software',price:'Set price',stock:3},
{id:'chatgpt',name:'ChatGPT',category:'AI & Software',price:'Set price',stock:2},
{id:'nitro-boost-1m',name:'1 Month Nitro Boost',category:'Discord',price:'Set price',stock:0},
{id:'lovable',name:'Lovable — FA 1 Month',category:'AI & Software',price:'Set price',stock:0},
{id:'nordvpn',name:'NordVPN — Private Lifetime',category:'VPN',price:'Set price',stock:8},
{id:'paramount',name:'Paramount — Lifetime',category:'Streaming',price:'Set price',stock:6},
{id:'disney-random',name:'Disney+ Random Sub',category:'Streaming',price:'Set price',stock:10},
{id:'capcut',name:'CapCut Pro — Lifetime',category:'AI & Software',price:'Set price',stock:6},
{id:'nitro-code',name:'Nitro Promocode — 3 Months',category:'Discord',price:'Set price',stock:3},
{id:'crunchyroll',name:'Crunchyroll — Lifetime',category:'Streaming',price:'Set price',stock:7},
{id:'hbo-max',name:'HBO MAX — Lifetime',category:'Streaming',price:'Set price',stock:5},
{id:'youtube-premium',name:'YouTube Premium — Invite Link',category:'Streaming',price:'Set price',stock:3},
{id:'server-boost',name:'Discord Server Boost',category:'Discord',price:'Set price',stock:8},
{id:'elevenlabs',name:'ElevenLabs — Lifetime',category:'AI & Software',price:'Set price',stock:0},
{id:'minecraft',name:'Minecraft Java & Bedrock — Full Access',category:'Gaming',price:'Set price',stock:2},
{id:'roblox',name:'Roblox Accounts — Full Access',category:'Gaming',price:'Set price',stock:3},
{id:'mullvad',name:'Mullvad VPN — Lifetime',category:'VPN',price:'Set price',stock:2},
{id:'uber-eats',name:'Uber Eats — Discounts',category:'Other',price:'Set price',stock:8},
{id:'gta-v',name:'GTA V Accounts — Full Access',category:'Gaming',price:'Set price',stock:3},
{id:'fivem',name:'FiveM Ready FA — Rockstar Account',category:'Gaming',price:'Set price',stock:100},
{id:'suppliers',name:'All My Suppliers',category:'Other',price:'Set price',stock:1},
{id:'valorant',name:'Valorant Account — 1–1000 Skins',category:'Gaming',price:'Set price',stock:35},
{id:'wondershare',name:'Wondershare — Lifetime',category:'AI & Software',price:'Set price',stock:24}
];