module.exports = [
  {id:'gemini-pro',name:'Gemini Pro [18 Months]',category:'AI / Tools',price:'€1.33',stock:0},
  {id:'netflix-4k',name:'Netflix 4K [LIFETIME]',category:'Streaming',price:'€0.21',stock:6},
  {id:'spotify',name:'Spotify Premium',category:'Streaming',price:'€2.10–€5.88',stock:2},
  {id:'vbucks',name:'1k-27k Vbucks Random Account [VERIFIED/UNVERIFED]',category:'Gaming',price:'€2.10',stock:0},
  {id:'server-boosts',name:'Server Boosts',category:'Discord',price:'€2.94–€7.70',stock:2},
  {id:'discord-members',name:'Discord Real Server Members [KEYS]',category:'Discord',price:'€2.80–€11.20',stock:3},
  {id:'mullvad',name:'Mullvad VPN [LIFETIME]',category:'VPN',price:'€2.65',stock:7},
  {id:'claude-keys',name:'Claude balance keys',category:'AI / Tools',price:'€5.60–€21.00',stock:2},
  {id:'chatgpt',name:'ChatGPT',category:'AI / Tools',price:'€1.61–€21.00',stock:2},
  {id:'nitro-boost',name:'1 Month Nitro Boost',category:'Discord',price:'€5.32',stock:0},
  {id:'paramount',name:'Paramount [LIFETIME]',category:'Streaming',price:'€0.20',stock:3},
  {id:'capcut',name:'Capcut Pro LIfetime',category:'Design',price:'€0.56–€3.43',stock:2},
  {id:'crunchyroll',name:'Crunchyroll [LIFETIME]',category:'Streaming',price:'€0.28',stock:8},
  {id:'minecraft',name:'Minecraft Java & Bedrock [Full Access]',category:'Gaming',price:'€5.11',stock:2},
  {id:'suppliers',name:'All My Suppliers',category:'Other',price:'€11.20',stock:999},
  {id:'disney',name:'Disney+ [LIFETIME]',category:'Streaming',price:'€0.42–€1.05',stock:3},
  {id:'movistar',name:'Movistar+ (ES) [Lifetime]',category:'Streaming',price:'€0.77',stock:0},
  {id:'hbo-max',name:'HBO MAX [LIFETIME]',category:'Streaming',price:'€0.63',stock:3},
  {id:'nordvpn',name:'NordVPN (Private) [LIFETIME]',category:'VPN',price:'€0.77',stock:0},
  {id:'youtube-premium',name:'YouTube Premium - [ INVITE LINK ON OWN ACCOUNT]',category:'Streaming',price:'€3.50–€13.65',stock:0},
  {id:'canva',name:'Canva Premium FA (3 years) [LIFETIME]',category:'Design',price:'€1.40',stock:0},
  {id:'clash-royale',name:'Clash Royale FA',category:'Gaming',price:'€1.40–€6.37',stock:4},
  {id:'gta-v',name:'GTA V Accounts (Full Access)',category:'Gaming',price:'€9.52',stock:3},
  {id:'uber-eats',name:'Uber Eats [Discounts]',category:'Other',price:'€4.20',stock:0},
  {id:'elevenlabs',name:'Elevenlabs [LIFETIME]',category:'AI / Tools',price:'€1.12',stock:0},
  {id:'nitro-promocode',name:'Nitro Promocode [3 Months]',category:'Discord',price:'€1.40',stock:0},
  {id:'wondershare',name:'Wondershare Lifetime',category:'Design',price:'€0.28',stock:2},
  {id:'duolingo',name:'Duolingo Lifetime',category:'Education',price:'€0.27',stock:1},
  {id:'lovable',name:'Lovable [FA 1 MONTH]',category:'AI / Tools',price:'€2.80',stock:0},
  {id:'valorant',name:'Valorant Account [1-1000 Skins]',category:'Gaming',price:'€0.11',stock:6},
  {id:'skins-vbucks',name:'1-1000 SKINS (+vbucks) | random account',category:'Gaming',price:'€0.42',stock:0},
  {id:'vps-1gb',name:'VPS 1GB',category:'VPS Hosting',price:'₹100',stock:0},
  {id:'vps-2gb',name:'VPS 2GB',category:'VPS Hosting',price:'₹150',stock:0},
  {id:'vps-4gb',name:'VPS 4GB',category:'VPS Hosting',price:'₹250',stock:0},
  {id:'vps-8gb',name:'VPS 8GB',category:'VPS Hosting',price:'₹400',stock:0},
  {id:'vps-16gb',name:'VPS 16GB',category:'VPS Hosting',price:'₹700',stock:0},
  {id:'vps-32gb',name:'VPS 32GB',category:'VPS Hosting',price:'₹1,200',stock:0}
];